name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - run: dotnet restore

      - run: dotnet build --configuration Release --no-restore

      - run: dotnet pack --configuration Release --no-build

      - uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: '**/*.nupkg'

  publish:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-runtime-version: '9.0.x'

      - uses: actions/download-artifact@v4
        with:
          name: nuget-package

      - run: dotnet nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate --no-symbols